### ISSUE TITLE
Use reink from MacOS using CUPS instead of raw-device

### ISSUE THREAD

**Issue by ghost** [lion-simba/reink#12]
Unfortunately, OSX does not create a raw-device in /dev. Printers are accessed through CUPS using e.g. `usb://fake/printer-id?serial=123456789`

**Comment by joyel24** [comment]
> Unfortunately, OSX does not create a raw-device in /dev. Printers are accessed through CUPS using e.g. `usb://fake/printer-id?serial=123456789`

How did you resolved it  ?

**Comment by dgerber** [comment]
>> Unfortunately, OSX does not create a raw-device in /dev. Printers are accessed through CUPS using e.g. `usb://fake/printer-id?serial=123456789`
> How did you resolved it  ?
(Maybe this helps <https://codeberg.org/atufi/reinkpy>. It uses libusb.)
